name: Reproduce setup-dotnet Permission Issue on Ubuntu Self-hosted Runners

on:
  workflow_dispatch:

jobs:
  ubuntu-dotnet-install-test:
    name: Ubuntu Dotnet Install Test (Self-hosted)
    runs-on: self-hosted
    strategy:
      matrix:
        ubuntu-label: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up runner label
        run: echo "Running on ${{ matrix.ubuntu-label }}"

      - name: Detect writable dotnet install directory
        id: dotnetdir
        shell: bash
        run: |
          # Try /usr/share/dotnet first
          if [ -d "/usr/share/dotnet" ]; then
            if [ -w "/usr/share/dotnet" ]; then
              echo "Writable: /usr/share/dotnet"
              echo "dir=/usr/share/dotnet" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "/usr/share/dotnet exists but is not writable"
            fi
          else
            # Try to create it if it doesn't exist
            mkdir -p /usr/share/dotnet 2>/dev/null
            if [ $? -eq 0 ]; then
              echo "Created and writable: /usr/share/dotnet"
              echo "dir=/usr/share/dotnet" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "Cannot create /usr/share/dotnet"
            fi
          fi

          # Next, try $HOME/.dotnet
          if [ -d "$HOME/.dotnet" ]; then
            if [ -w "$HOME/.dotnet" ]; then
              echo "Writable: $HOME/.dotnet"
              echo "dir=$HOME/.dotnet" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "$HOME/.dotnet exists but is not writable"
            fi
          else
            mkdir -p "$HOME/.dotnet"
            if [ $? -eq 0 ]; then
              echo "Created and writable: $HOME/.dotnet"
              echo "dir=$HOME/.dotnet" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "Cannot create $HOME/.dotnet"
            fi
          fi

          # Last, try $RUNNER_TEMP/.dotnet
          mkdir -p "$RUNNER_TEMP/.dotnet"
          if [ $? -eq 0 ]; then
            echo "Created and writable: $RUNNER_TEMP/.dotnet"
            echo "dir=$RUNNER_TEMP/.dotnet" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Cannot create $RUNNER_TEMP/.dotnet, setup will likely fail!"
            echo "dir=" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Setup .NET using detected install directory
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          dotnet-install-dir: ${{ steps.dotnetdir.outputs.dir }}

      - name: Print dotnet info and installation directories
        run: |
          echo "Dotnet info:"
          dotnet --info || echo "dotnet not installed"
          echo "Used install directory: ${{ steps.dotnetdir.outputs.dir }}"
          echo "Checking /usr/share/dotnet:"
          ls -al /usr/share/dotnet || echo "/usr/share/dotnet does not exist or inaccessible"
          echo "Checking /usr/lib/dotnet:"
          ls -al /usr/lib/dotnet || echo "/usr/lib/dotnet does not exist or inaccessible"
          echo "Checking $HOME/.dotnet:"
          ls -al $HOME/.dotnet || echo "$HOME/.dotnet does not exist or inaccessible"
          echo "Checking $RUNNER_TEMP/.dotnet:"
          ls -al $RUNNER_TEMP/.dotnet || echo "$RUNNER_TEMP/.dotnet does not exist or inaccessible"
          echo "Current user:"
          whoami
        shell: bash