name: Reproduce setup-dotnet Permission Issue on Ubuntu Self-hosted Runners

on:
  workflow_dispatch:

jobs:
  ubuntu-dotnet-install-test:
    name: Ubuntu Dotnet Install Test (Self-hosted)
    runs-on: self-hosted
    strategy:
      matrix:
        ubuntu-label: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up runner label
        run: echo "Running on ${{ matrix.ubuntu-label }}"

      - name: Determine writable dotnet install directory
        id: dotnet-dir
        shell: bash
        run: |
          # 1. Priority: User-supplied DOTNET_INSTALL_DIR
          if [ -n "${DOTNET_INSTALL_DIR}" ]; then
            echo "Using user-supplied DOTNET_INSTALL_DIR: ${DOTNET_INSTALL_DIR}"
            echo "install-dir=${DOTNET_INSTALL_DIR}" >> $GITHUB_OUTPUT
            exit 0
          fi

          # 2. Priority: /usr/share/dotnet if writable
          if [ -d "/usr/share/dotnet" ]; then
            if [ -w "/usr/share/dotnet" ]; then
              echo "/usr/share/dotnet exists and is writable."
              echo "install-dir=/usr/share/dotnet" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "/usr/share/dotnet exists but is NOT writable."
            fi
          else
            # Try to create the directory to check permissions
            mkdir -p /usr/share/dotnet 2>/dev/null
            if [ $? -eq 0 ]; then
              echo "Created /usr/share/dotnet, directory is writable."
              echo "install-dir=/usr/share/dotnet" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "Cannot create /usr/share/dotnet, directory is NOT writable."
            fi
          fi

          # 3. Priority: $HOME/.dotnet if writable
          if [ -d "$HOME/.dotnet" ]; then
            if [ -w "$HOME/.dotnet" ]; then
              echo "$HOME/.dotnet exists and is writable."
              echo "install-dir=$HOME/.dotnet" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "$HOME/.dotnet exists but is NOT writable."
            fi
          else
            mkdir -p "$HOME/.dotnet"
            if [ $? -eq 0 ]; then
              echo "Created $HOME/.dotnet, directory is writable."
              echo "install-dir=$HOME/.dotnet" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "Cannot create $HOME/.dotnet, directory is NOT writable."
            fi
          fi

          # 4. Priority: $RUNNER_TEMP/.dotnet as last fallback
          mkdir -p "$RUNNER_TEMP/.dotnet"
          if [ $? -eq 0 ]; then
            echo "Created $RUNNER_TEMP/.dotnet, directory is writable."
            echo "install-dir=$RUNNER_TEMP/.dotnet" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Cannot create $RUNNER_TEMP/.dotnet, action will likely fail."
            echo "install-dir=" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Setup .NET with chosen install directory
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          dotnet-install-dir: ${{ steps.dotnet-dir.outputs.install-dir }}

      - name: Print dotnet info and installation directories
        run: |
          echo "Dotnet info:"
          dotnet --info || echo "dotnet not installed"
          echo "Used install directory: ${{ steps.dotnet-dir.outputs.install-dir }}"
          echo "Checking /usr/share/dotnet:"
          ls -al /usr/share/dotnet || echo "/usr/share/dotnet does not exist or inaccessible"
          echo "Checking /usr/lib/dotnet:"
          ls -al /usr/lib/dotnet || echo "/usr/lib/dotnet does not exist or inaccessible"
          echo "Checking $HOME/.dotnet:"
          ls -al $HOME/.dotnet || echo "$HOME/.dotnet does not exist or inaccessible"
          echo "Checking $RUNNER_TEMP/.dotnet:"
          ls -al $RUNNER_TEMP/.dotnet || echo "$RUNNER_TEMP/.dotnet does not exist or inaccessible"
          echo "Current user:"
          whoami
        shell: bash